# Cloud Build configuration for deploying to Google Cloud Run
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-f', 'Dockerfile.gcp',
      '-t', 'gcr.io/$PROJECT_ID/mineral-rights-api:$BUILD_ID',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mineral-rights-api:$BUILD_ID']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'mineral-rights-api',
      '--image', 'gcr.io/$PROJECT_ID/mineral-rights-api:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '2Gi',
      '--cpu', '2',
      '--timeout', '300',
      '--max-instances', '10',
      '--set-env-vars', 'GCS_BUCKET_NAME=mineral-rights-storage-$PROJECT_ID,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=us-central1,TASK_QUEUE_NAME=mineral-rights-queue'
    ]

  # Build the job worker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-f', 'Dockerfile.job',
      '-t', 'gcr.io/$PROJECT_ID/mineral-rights-worker:$BUILD_ID',
      '.'
    ]

  # Push the job worker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mineral-rights-worker:$BUILD_ID']

  # Deploy job worker to Cloud Run Jobs
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'jobs', 'deploy', 'mineral-rights-worker',
      '--image', 'gcr.io/$PROJECT_ID/mineral-rights-worker:$BUILD_ID',
      '--region', 'us-central1',
      '--memory', '4Gi',
      '--cpu', '2',
      '--max-retries', '3',
      '--parallelism', '1',
      '--task-timeout', '3600',
      '--set-env-vars', 'GCS_BUCKET_NAME=mineral-rights-storage-$PROJECT_ID,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=us-central1'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/mineral-rights-api:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/mineral-rights-worker:$BUILD_ID'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
