# Cloud Build configuration for deploying to Google Cloud Run
# Uses Artifact Registry (gcr.io is deprecated for new projects)
substitutions:
  _REGION: us-central1
  _AR_REPO: mineral-rights

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'Dockerfile.gcp',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/mineral-rights-api:$BUILD_ID',
      '.'
    ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/mineral-rights-api:$BUILD_ID']

  # Deploy container image to Cloud Run (mineral-rights project; no old-project credentials)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'mineral-rights-api',
      '--image', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/mineral-rights-api:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '2Gi',
      '--cpu', '2',
      '--timeout', '300',
      '--max-instances', '10',
      '--set-env-vars', 'GCS_BUCKET_NAME=mineral-rights-storage-$PROJECT_ID,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=us-central1,TASK_QUEUE_NAME=mineral-rights-queue',
      '--set-secrets', 'ANTHROPIC_API_KEY=anthropic-api-key:latest'
    ]

  # Build and deploy job worker (same project env vars, no old-project credentials)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'Dockerfile.job',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/mineral-rights-worker:$BUILD_ID',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/mineral-rights-worker:$BUILD_ID']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'jobs', 'deploy', 'mineral-rights-worker',
      '--image', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/mineral-rights-worker:$BUILD_ID',
      '--region', 'us-central1',
      '--memory', '4Gi',
      '--cpu', '2',
      '--max-retries', '3',
      '--parallelism', '1',
      '--task-timeout', '3600',
      '--set-env-vars', 'GCS_BUCKET_NAME=mineral-rights-storage-$PROJECT_ID,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=us-central1',
      '--set-secrets', 'ANTHROPIC_API_KEY=anthropic-api-key:latest'
    ]

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/mineral-rights-api:$BUILD_ID'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/mineral-rights-worker:$BUILD_ID'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
