#!/usr/bin/env python3
"""
Create Real Google Cloud Service Account
This script will guide you through creating a real service account
"""

def main():
    print("🚀 Create Real Google Cloud Service Account")
    print("=" * 60)
    print()
    print("📋 STEP 1: Go to Google Cloud Console")
    print("   https://console.cloud.google.com/")
    print()
    print("📋 STEP 2: Select your project")
    print("   Project ID: deed-boundary-250831-29868")
    print()
    print("📋 STEP 3: Enable Document AI API")
    print("   1. Go to APIs & Services > Library")
    print("   2. Search for 'Document AI API'")
    print("   3. Click 'Enable'")
    print()
    print("📋 STEP 4: Create Service Account")
    print("   1. Go to IAM & Admin > Service Accounts")
    print("   2. Click 'Create Service Account'")
    print("   3. Name: mineral-rights-processor")
    print("   4. Description: Service account for Document AI processing")
    print("   5. Click 'Create and Continue'")
    print()
    print("📋 STEP 5: Grant Permissions")
    print("   1. Add role: 'Document AI API User'")
    print("   2. Add role: 'Storage Object Viewer' (if using GCS)")
    print("   3. Click 'Continue'")
    print()
    print("📋 STEP 6: Create Key")
    print("   1. Click on the created service account")
    print("   2. Go to 'Keys' tab")
    print("   3. Click 'Add Key' > 'Create new key'")
    print("   4. Choose 'JSON' format")
    print("   5. Click 'Create'")
    print("   6. Download the JSON file")
    print()
    print("📋 STEP 7: Upload to Render")
    print("   1. Go to your Render dashboard")
    print("   2. Go to your backend service")
    print("   3. Go to Environment tab")
    print("   4. Go to Secret Files section")
    print("   5. Click 'Edit'")
    print("   6. Delete the old service-account.json")
    print("   7. Upload the new JSON file you downloaded")
    print("   8. Save changes")
    print()
    print("🎯 This will give you REAL credentials that work!")
    print()
    print("⚠️  IMPORTANT: The current file has fake credentials")
    print("   That's why you're getting the base64 decode error")
    print()
    print("=" * 60)
    print("🔍 Follow these steps to get real working credentials")

if __name__ == "__main__":
    main()
